#!/usr/bin/env zsh
#*****************************************************************************************
# get_sudo_password
#
# This routine will prompt the user to enter their password to put the shell in super user
# mode for file I/O and command execution
#
# Author   :  Gary Ash <gary.ash@icloud.com>
# Created  :  11-Jan-2020  2:23pm
# Modified :  11-Jan-2020  2:23pm
#
# Copyright © 2020 By Gee Dbl A All rights reserved.
#*****************************************************************************************
get_sudo_password() {
	local SUDO_PASSWORD

	sudo --reset-timestamp
	if ! sudo --validate --non-interactive &>/dev/null; then
		while true; do
			echo -n "Enter pasword for sudo: " >&2
			read -rs SUDO_PASSWORD
			echo ""							  >&2
			if sudo --validate --stdin  <<<"$SUDO_PASSWORD" 2> /dev/null; then
				break
			fi
		done
	fi
	echo "$SUDO_PASSWORD"
}
get_sudo_password