#!/usr/bin/env zsh
#*****************************************************************************************
# stay_awake
#
# This command will cause the computer to stay awake until cancel_awake is called
#
# Author   :  Gary Ash <gary.ash@icloud.com>
# Created  :  18-Aug-2023  8:11pm
# Modified :
#
# Copyright © 2023 By Gee Dbl A All rights reserved.
#*****************************************************************************************
stay_awake() {
	caffeinate -dis &>/dev/null &
	export CAFFEINATE=$!
}
stay_awake
