#!/usr/bin/env zsh
#*****************************************************************************************
# stop_persistant_sudo
#
# This routine will stop a persistant sudo session
#
# Author   :  Gary Ash <gary.ash@icloud.com>
# Created  :  18-Aug-2023  8:11pm
# Modified :
#
# Copyright © 2023 By Gee Dbl A All rights reserved.
#*****************************************************************************************
stop_persistant_sudo() {
	if [[ -n $ZSH_VERSION ]]; then
		setopt local_options no_monitor
	fi

	kill $SUDO_SHELL_PID
	kill $CAFFEINATE
	wait
	unset SUDO_SHELL_PID
	unset CAFFEINATE
	unset SUDO_PASSWORD

	if [[ -n $ZSH_VERSION ]]; then
		setopt monitor
	fi

	sudo --reset-timestamp
}
stop_persistant_sudo
