#!/usr/bin/env zsh
#*****************************************************************************************
# cdf
#
# Change the directory to the one listed in the top Finder window
#
# Author   :  Gary Ash <gary.ash@icloud.com>
# Created  :  11-Jan-2020  2:23pm
# Modified :  11-Jan-2020  2:23pm
#
# Copyright © 2020 By Gee Dbl A All rights reserved.
#*****************************************************************************************
cd "$(osascript -e 'tell app "Finder" to POSIX path of (insertion location as alias)')" || return
