#!/usr/bin/env zsh
#*****************************************************************************************
# cdf
#
# Change the directory to the one listed in the top Finder window
#
# Author   :  Gary Ash <gary.ash@icloud.com>
# Created  :  18-Aug-2023  8:11pm
# Modified :
#
# Copyright © 2023 By Gee Dbl A All rights reserved.
#*****************************************************************************************
cd "$(osascript -e 'tell app "Finder" to POSIX path of (insertion location as alias)')" || return
