#!/usr/bin/env zsh
#*****************************************************************************************
# cdl
#
# Change the directory to the named one and then list its contents with exa
#
# Author   :  Gary Ash <gary.ash@icloud.com>
# Created  :  11-Jan-2020  2:23pm
# Modified :  11-Jan-2020  2:23pm
#
# Copyright © 2020 By Gee Dbl A All rights reserved.
#*****************************************************************************************
cd "$@" || return
exa --long -all --git --group --group-directories-first --color=always
