#!/usr/bin/env zsh
#****************************************************************************************
# clean
#
# Clean the junk files from the current directory tree and Trash
#
# Author   :  Gary Ash <gary.ash@icloud.com>
# Created  :  18-Aug-2023  8:11pm
# Modified :
#
# Copyright © 2023 By Gee Dbl A All rights reserved.
#****************************************************************************************
search='.'
if [ "$1" ]; then
	search=${1}
fi
find "$search" \( -name "*~" -or -name ".*~" -or -name "#*#" -or -name ".#*#" -or -name "*.o" -or -name "*(deleted*" -or -name "*conflicted*" -or -name "*.DS_Store" \) -exec rm -frv {} \; &>/dev/null
rm -rf ~/.Trash/ &>/dev/null
