#!/usr/bin/env zsh
#*****************************************************************************************
# generate-ignore
#
# Generate a .gitignore for a project based the languages, IDE's, etc specified
#
# Author   :  Gary Ash <gary.ash@icloud.com>
# Created  :  11-Jan-2020  2:23pm
# Modified :  17-Jan-2020  8:48pm
#
# Copyright © 2020 By Gee Dbl A All rights reserved.
#*****************************************************************************************
stuff=""

for s in "$@"; do
	out=$(curl -sL "https://www.gitignore.io/api/$s")
	case $out in
	    *ERROR*)
		echo "Unknown ignore type - $s"
		return 1
	    ;;
	esac

	if [[ -n "$stuff" ]]; then
		stuff+=","
	fi
	stuff+="$s"
done
curl -sL "https://www.gitignore.io/api/$stuff" > .gitignore
