#!/usr/bin/env zsh
#*****************************************************************************************
# git-rm-hist
#
# This script command will remove the named file from git history
#
# git-rm-hist <path of file that should be forgotten>
#
# Author   :  Gary Ash <gary.ash@icloud.com>
# Created  :  20-Jul-2020  9:37pm
# Modified :  20-Jul-2020  9:43pm
#
# Copyright © 2020 By Gee Dbl A All rights reserved.
#*****************************************************************************************

git filter-branch --index-filter "git rm -rf --cached --ignore-unmatch $@" HEAD
rm -rf .git/refs/original/
git reflog expire --all
git gc --aggressive --prune
