#!/usr/bin/env zsh
#*****************************************************************************************
# mkd
#
# Make the directory/directory structure named on the command line and enter it
#
# Author   :  Gary Ash <gary.ash@icloud.com>
# Created  :  18-Aug-2023  8:11pm
# Modified :
#
# Copyright © 2023 By Gee Dbl A All rights reserved.
#*****************************************************************************************
mkdir -p "$@"
cd "$_" || return
