#!/usr/bin/env zsh
#*****************************************************************************************
# pretty_var
#
# Break up the PATH or PATH style environment variable named on the command line at the
# colon seperator for easier reading
#
# Author   :  Gary Ash <gary.ash@icloud.com>
# Created  :  18-Aug-2023  8:11pm
# Modified :
#
# Copyright © 2023 By Gee Dbl A All rights reserved.
#*****************************************************************************************
echo "$1" | tr -s ":" '\n'
