#!/usr/bin/env zsh
#*****************************************************************************************
# pretty_var
#
# Break up the PATH or PATH style environment variable named on the command line at the
# colon seperator for easier reading
#
# Author   :  Gary Ash <gary.ash@icloud.com>
# Created  :  11-Jan-2020  2:23pm
# Modified :  11-Jan-2020  2:23pm
#
# Copyright © 2020 By Gee Dbl A All rights reserved.
#*****************************************************************************************
echo "$1" | tr -s ":" '\n'