#!/usr/bin/env zsh
#*****************************************************************************************
# xcode
#
# Open the Xcode workspace or project in this directory tree
#
# Author   :  Gary Ash <gary.ash@icloud.com>
# Created  :  18-Aug-2023  8:11pm
# Modified :
#
# Copyright © 2023 By Gee Dbl A All rights reserved.
#*****************************************************************************************
open $(find . -name *.xcworkspace || find . -name *.xcodeproj)
