#!/usr/bin/env zsh
#*****************************************************************************************
# xcode
#
# Open the Xcode workspace or project in this directory tree
#
# Author   :  Gary Ash <gary.ash@icloud.com>
# Created  :  11-Jan-2020  2:23pm
# Modified :  11-Jan-2020  2:23pm
#
# Copyright © 2020 By Gee Dbl A All rights reserved.
#*****************************************************************************************
open $(find . -name *.xcworkspace || find . -name *.xcodeproj)
