#!/usr/bin/env zsh
#*****************************************************************************************
# zcompile-lib
#
# This script command will recompile my Zsh scripting library and comments
#
# Author   :  Gary Ash <gary.ash@icloud.com>
# Created  :  18-Aug-2023  8:11pm
# Modified :  24-Dec-2023  2:52pm
#
# Copyright © 2023 By Gee Dbl A All rights reserved.
#***************************************************************************************** 

find -x /opt/lib/geedbla/zsh -name "*.DS_Store" -type f -delete
for file (/usr/local/lib/geedbla/zsh/**/^*.zwc(N.)); do
	zcompile $file
done
find /opt/lib/geedbla/zsh -type f -exec chmod 644 {} \;
