#!/usr/bin/env bash
shopt -s extglob
#*****************************************************************************************
# pre-commit
#
# This is a git pre-commit hook script that will format source file before submitting the
# actual commit to the target repository
#
# Author   :  Gary Ash <gary.ash@icloud.com>
# Created  :  25-Jul-2023  1:46pm
# Modified :  10-Feb-2024  7:54pm
#
# Copyright © 2023-2024 By Gee Dbl A All rights reserved.
#*****************************************************************************************
swift=".*\.swift$ "
objc=".*\.(m|mm|pch|h|hh)$"
cfiles=".*\.(hpp|hxx|c|cc|cpp|cxx|cs|jav|java)$"

IFS=$'\n'

for commit in $(git diff --cached --name-only --diff-filter=ACM); do
	for filename in "${commit[@]}"; do
		if [[ $filename =~ $swift ]]; then
			if which swiftformat >/dev/null; then
				swiftformat --config "$HOME/.config/.swiftformat" "${filename}"
				git update-index --really-refresh --again "${filename}"
			fi
		elif [[ $filename =~ $objc ]]; then
			if which uncrustify >/dev/null; then
				uncrustify -l OC+ --replace --no-backup -c "$HOME/.config/.uncrustify" "${filename}"
				git update-index --really-refresh --again "${filename}"
			fi
		elif [[ $filename =~ $cfiles ]]; then
			if which uncrustify >/dev/null; then
				uncrustify --replace --no-backup -c "$HOME/.config/.uncrustify" "${filename}"
				git update-index --really-refresh --again "${filename}"
			fi
		else
			read -r line <"${filename}"
			if [[ $line =~ ^\#\!.*perl ]]; then
				if which perltidyrc >/dev/null; then
					perltidy -b -bext='/' --profile="$HOME/.config/.perltidyrc" "${filename}"
					git update-index --really-refresh --again "${filename}"
				fi
			elif [[ $line =~ ^\#\!.*python ]]; then
				if which black >/dev/null; then
					black --config "$HOME/.config/black" --quiet "${filename}"
					git update-index --really-refresh --again "${filename}"
				fi
			elif [[ $line =~ ^\#\!.*(bash|zsh|sh)$ ]]; then
				if which shfmt >/dev/null; then
					shfmt -s -ci -i 0 -w -ln bash "${filename}"
					git update-index --really-refresh --again "${filename}"
				fi
			fi
		fi
	done
done
